print('Déroulement de la bataille navale', end='\n * ')
print('Le joueur A place ses bateaux sur la gille', end='\n * ')
print('Le joueur B place ses bateaux sur la grille', end='\n * ')
print("Le joueur A attaque l'adversaire en tirant sur une coordonée de la grille du joueur B", end='\n ** ')
print("Si le joueur A touche un bateau du joueur B, alors c'est touché", end='\n ** ')
print("Si en plus d'avoir touché, le bateau est coulé, alors c'est touché coulé", end='\n ** ')
print("Si le joueur A touche l'eau du joueur B, alors c'est perdu et au tour du joueur suivant", end='\n * ')
print("Les 3 étapes ci-dessus sont réitérés jusqu'à la fin du jeu", end='\n * ')
print("Le jeu se termine lorsqu'un des deux joueurs a coulé tous les bateaux de l'adversaire")
